version: "3.8"
services:
    mysql-server:
        image: mysql
        platform: linux/x86_64
        ports:
            - 3399:3306
        restart: always
        volumes:
            - ./mysql/data:/var/lib/mysql
            # - ./mysql/sql/:/docker-entrypoint-initdb.d/
        environment:
            MYSQL_ROOT_PASSWORD: 
            MYSQL_USER: user
            MYSQL_PASSWORD: user
            TZ: Asia/Bangkok
            

    web:
        build: ./www
        restart: always
        ports:
            - 8080:80
        volumes:
            - ./www:/var/www/html/
        depends_on:
            - "mysql-server"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - 8888:80
        restart: always
        environment:
            - PMA_HOST=mysql-server
            - TZ=Asia/Ho_Chi_Minh

        depends_on:
            - "mysql-server"
